### ISSUE TITLE
Centering Main Menu and Search Box

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#11]
Site Area : **Theme**, Priority : **Low**
Main Menu and search box should both be centered on the screen, as you can see in the screenshot:

![hk_centering_menu_and_seach](https://cloud.githubusercontent.com/assets/389844/14423130/7347d0da-ffda-11e5-97c6-834b144c89ca.png)

**Comment by heliogabal** [comment]
Main-Menu is centered, but somehow the margin-top got screwed. Instead of 44px, it needs to be 59px now in order to bottom-align with logo and header.

**Comment by heliogabal** [comment]
Centering of Main-Menu leads to the Service Menu Icons being invisible now. See http://addweb.dev.drupalforgood.eu/

**Comment by heliogabal** [comment]
The search box is centered, but the dropdown-select is displaced by some pixels when it is opened and the close Icon is misplaced and not sitting in the corner any longer. Should be `.ui-dialog .ui-dialog-titlebar .ui-dialog-titlebar-close {
    margin: -23px -23px 0 0;
    ...
}`
now.

![search-box-alignment](https://cloud.githubusercontent.com/assets/389844/14554225/b5925456-02eb-11e6-8489-c0431b83e62d.png)

**Comment by heliogabal** [comment]
Also, while I like the search box now being just as big as it needs to be (there was some space before catering for the search result counter and reset button that appears once something is selected), now the result counter/reset is hidden altogether. That might work once issue #7 is fixed, but for now, there is not enough feedback for the user.

**Comment by vivek-addweb** [comment]
Hi Rainer
Fixed issue of icons. And Work in progress for drop down alignment issue in Search box.

**Comment by heliogabal** [comment]
Hi Vivek, 
there are two comment errors in commit 8a6e5b22e7e6fdbfe2191834f9e68d4073ba3957 in script.js. One I fixed (missing / before comment *), but the other one is an open comment and I don't know how much you want to comment there, so you have to fix this yourself. 

Once fixed, I can check.

**Comment by heliogabal** [comment]
ah, I see that probably the /\* from the first line got accidentally inserted in line 332... drop down alignment still seems to randomly be a bit of on the right side, on the left it is ok. Weird. Will check more thoroughly tomorrow.

**Comment by heliogabal** [comment]
Hi Vivek, 
I'm afraid, but this is not fully fixed yet. Though the search select aligns well on the left side now, the right side is still off by one pixel when the select opens towards the top - unfortunately, it's off by 1px to the right in borrough and price, 1px to the left in space... that's in Firefox 45.0.2 on Linux at least. If you tell me it's fine on Windows, I'd be happy to commit nevertheless. 

![offset_borrough](https://cloud.githubusercontent.com/assets/389844/14780264/8009fd54-0adc-11e6-993e-b4a27acaa6cc.png)

![offset_space](https://cloud.githubusercontent.com/assets/389844/14780275/8713738c-0adc-11e6-9640-bdf6dfd08878.png)

But what is worse, on Chrome, once I opened a lower select and close it again, the whole form "jumps" to the top inside the search box, which really makes it look buggy.  That needs to be fixed.

![search_jumpy_chrome](https://cloud.githubusercontent.com/assets/389844/14780343/c5d51ff8-0adc-11e6-9a15-6ebce7195e7d.png)

This was all not the case before as you can compare with the live site, so it must be something that got introduced by you.

PS: The Close X is still not sitting where it was and is supposed to be - exactly centered on the top right corner.

**Comment by vivek-addweb** [comment]
Hi Rainer
I have tested on all browsers of windows, Mac & Linux. But the issue only appears in Linux.
Fixed issue of form jumps to the top inside the search box.

**Comment by heliogabal** [comment]
Hi Vivek, ok, then it's ok. We have a very low percentage of linux visitors, so we can live with that. Thanks for extensive testing.
